version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ab_finance_db
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: ab_finance_web
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://finance_user:finance_password@db:5432/finance_db
      - SECRET_KEY=django-insecure-(--6=uyvxyimomjn#&*81uim8x)(l=6zvd4puw952-o@zc7cqw
      - DEBUG=1

volumes:
  postgres_data:
