# Generated by Django 5.0.3 on 2026-04-03 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Entrada')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
                ('installment_value', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor da Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento Inicial')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Método de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago S/N')),
                ('has_nf', models.BooleanField(default=False, verbose_name='NF')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_set', to='core.payment')),
            ],
        ),
    ]
