# Generated by Django 5.0.3 on 2026-04-03 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='down_payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Entrada'),
        ),
    ]
