# Generated by Django 5.0.3 on 2026-04-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_down_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
    ]
