# Generated by Django 5.0.3 on 2026-04-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_alter_payment_installments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone',
        ),
    ]
