# Generated by Django 5.0.3 on 2026-04-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_payment_cpf_remove_payment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='down_payment_is_paid',
            field=models.BooleanField(default=False, verbose_name='Entrada Paga?'),
        ),
    ]
