# Generated by Django 5.0.3 on 2026-05-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_data_nascimento_cliente_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
    ]
